### ISSUE TITLE
bug: Direcotyr Not Found ./vscode/typings

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/ionic-angular-standalone-codemods#44]
### Prerequisites

- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-angular-standalone-codemods) that already report this problem, without success.

### Codemod version

0.3.0

### Current Behavior

I run `npx @ionic/angular-standalone-codemods`.

I'm prompted with the dry run option. 

Regardless of the option I select I get the following error afterwards.

```
DirectoryNotFoundError: Directory not found: /xxxxxxxxxxx/.vscode/typings
    at RealFileSystemHost.getDirectoryNotFoundErrorIfNecessary (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/@ts-morph/common/dist/ts-morph-common.js:1965:50)
    at RealFileSystemHost.readDirSync (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/@ts-morph/common/dist/ts-morph-common.js:1874:24)
    at TransactionalFileSystem.readDirSync (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/@ts-morph/common/dist/ts-morph-common.js:2501:55)
    at FileUtils.getDescendantDirectories (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/@ts-morph/common/dist/ts-morph-common.js:1547:47)
    at getDescendantDirectories.next (<anonymous>)
    at FileUtils.getDescendantDirectories (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/@ts-morph/common/dist/ts-morph-common.js:1551:30)
    at getDescendantDirectories.next (<anonymous>)
    at FileUtils.getDescendantDirectories (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/@ts-morph/common/dist/ts-morph-common.js:1551:30)
    at getDescendantDirectories.next (<anonymous>)
    at DirectoryCoordinator.addDirectoryAtPathIfExists (/Users/jamesonparker/.npm/_npx/ff04957b6f1fa49f/node_modules/ts-morph/dist/ts-morph.js:18826:24) {
  path: '/xxxxxxxxxxx/.vscode/typings',
  code: 'ENOENT'
  ```
  
  I have checked the .vscode directory and I only have a .launch file in there. So I'm not sure if I'm missing something or what. 
  
  

### Expected Behavior

I would expect the migration process to run

### Steps to Reproduce

1. `npx @ionic/angular-standalone-codemods`
2. Select either option for Dry Run
3. Error shows up

**Comment by liamdebeasi** [comment]
Hey there,

Can you provide a GitHub repo that I can use to reproduce the issue? The team is unable to reproduce this issue using a new project.

**Comment by selected-pixel-jameson** [comment]
@liamdebeasi Unfortunately I cannot. This is a client project and I cannot share the code without legal ramifications. I would assume that it has something to do with including cordova plugins. 

Specifically `"cordova-plugin-purchase": "^13.5.0",`

The Angular migration tool worked without any issues, but that obviously isn't going to handle migrating all of the Ion Components. I manually ended up doing this. Took me about 8-10 hours.

**Comment by JoranLive** [comment]
I hadd simular issue.

It was due to the file 'cordova-typings.d.ts':

`<reference path="..\.vscode\typings\cordova-ionic\plugins\keyboard.d.ts"/>
<reference path="..\.vscode\typings\jquery\jquery.d.ts"/>
`
